---
title: "R NBA trade chord diagram"
output: html_notebook
---

 Install & load the 'jsonlite' package to read in the json files.

```{r}
library(jsonlite)
# 'circlize' has a chordDiagram() method, but 'chorddiag' is another option. Not sure which is better...
library(circlize)
library(chorddiag)
#library(purrr)
```

Import data from JSON files.

```{r}
nba_trade_data <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/js_chord/nba_matrix_array.json", simplifyMatrix = T)
```

```{r}
nba_df <- data.frame(nba_trade_data)

names(nba_df) <- team_names
row.names(nba_df) = c(colnames(nba_df))
```


```{r}
team_names <- c("ATL", "BKN", "BOS", "CHA", "CHI", "CLE", "DAL", "DEN", "DET", "GSW", "HOU", "IND", "LAC", "LAL", "MEM", "MIA", "MIL", "MIN", "NOP", "NYK", "OKC", "ORL", "PHI", "PHO", "POR", "SAC", "SAS", "TOR", "UTA", "WAS")
```

# Import data seperated by year from INDIVIDUAL json files...
Will just try most recent 10 years first.

```{r}
nba_trade_data_2017 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2017.json", simplifyDataFrame = T)
nba_trade_data_2017 <- data.frame(nba_trade_data_2017)

nba_trade_data_2016 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2016.json", simplifyDataFrame = T)
nba_trade_data_2016 <- data.frame(nba_trade_data_2016)

nba_trade_data_2015 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2015.json", simplifyDataFrame = T)
nba_trade_data_2015 <- data.frame(nba_trade_data_2015)

nba_trade_data_2014 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2014.json", simplifyDataFrame = T)
nba_trade_data_2014 <- data.frame(nba_trade_data_2014)

nba_trade_data_2013 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2013.json", simplifyDataFrame = T)
nba_trade_data_2013 <- data.frame(nba_trade_data_2013)

nba_trade_data_2012 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2012.json", simplifyDataFrame = T)
nba_trade_data_2012 <- data.frame(nba_trade_data_2012)

nba_trade_data_2011 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2011.json", simplifyDataFrame = T)
nba_trade_data_2011 <- data.frame(nba_trade_data_2011)

nba_trade_data_2010 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2010.json", simplifyDataFrame = T)
nba_trade_data_2010 <- data.frame(nba_trade_data_2010)

nba_trade_data_2009 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2009.json", simplifyDataFrame = T)
nba_trade_data_2009 <- data.frame(nba_trade_data_2009)

nba_trade_data_2008 <- fromJSON("~/Documents/DevStuff/DataSciProjects/NBAPlayerMovement/json_files/nba_matrix_year_2008.json", simplifyDataFrame = T)
nba_trade_data_2008 <- data.frame(nba_trade_data_2008)
```

```{r}
length(nba_trade_data_by_year)
nba_trade_data_by_year[[1]]
```

```{r}
nba_df_by_year <- data.frame(nba_trade_data_by_year)
```

### Rename the columns/idx for each with the team_names vector.
```{r}
names(nba_trade_data_2017) <- team_names
row.names(nba_trade_data_2017) = c(colnames(nba_trade_data_2017))

names(nba_trade_data_2016) <- team_names
row.names(nba_trade_data_2016) = c(colnames(nba_trade_data_2016))

names(nba_trade_data_2015) <- team_names
row.names(nba_trade_data_2015) = c(colnames(nba_trade_data_2015))

names(nba_trade_data_2014) <- team_names
row.names(nba_trade_data_2014) = c(colnames(nba_trade_data_2014))

names(nba_trade_data_2013) <- team_names
row.names(nba_trade_data_2013) = c(colnames(nba_trade_data_2013))

names(nba_trade_data_2012) <- team_names
row.names(nba_trade_data_2012) = c(colnames(nba_trade_data_2012))

names(nba_trade_data_2011) <- team_names
row.names(nba_trade_data_2011) = c(colnames(nba_trade_data_2011))

names(nba_trade_data_2010) <- team_names
row.names(nba_trade_data_2010) = c(colnames(nba_trade_data_2010))

names(nba_trade_data_2009) <- team_names
row.names(nba_trade_data_2009) = c(colnames(nba_trade_data_2009))

names(nba_trade_data_2008) <- team_names
row.names(nba_trade_data_2008) = c(colnames(nba_trade_data_2008))
```

Now refer to this tutorial to make a shiny dash with interactivity:
http://datascience-enthusiast.com/R/Interactive_chord_diagrams_R.html

## Plotting the chord diagram

```{r}
# chordDiagram(nba_matrix)
nba_trade_data_2009_matrix <- as.matrix(nba_trade_data_2009)
chorddiag(nba_trade_data_2009_matrix, showTicks = F, groupnameFontsize = 12, groupnamePadding = 5) #, type = "directional", showTicks = F, groupnameFontsize = 14, groupnamePadding = 10, margin = 90)
```




